services:
  api:
    # בונה את התמונה מה-Dockerfile שכבר נמצא בשורש הריפו
    build:
      context: .
      dockerfile: Dockerfile
    image: urlshortener-api:local
    container_name: urlshortener-api
    ports:
      # מארח:קונטיינר — ניגשים ל- http://localhost:8080
      - "8080:8080"
    environment:
      # לא חובה אם כבר הוספת את השורה ב-Program.cs, אבל טוב שיהיה
      - PORT=8080
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      # ממפים תיקייה מקומית לשביל שבו ה-DB נשמר בקונטיינר
      # כך הקובץ יישמר מחוץ לקונטיינר ולא ייעלם כשעוצרים אותו
      - ./DataDocker:/app/Data
    restart: unless-stopped
